Repository Lets-Be-Friendly-Team/daeng-ggu-backend, pull requests merged in 2024-12, with the labels that each got.

#26 feature/#33-table-column-case-change
  src/main/java/com/ureca/profile/domain/PortfolioImg.java
  src/main/java/com/ureca/profile/infrastructure/ImgRepository.java
  src/main/java/com/ureca/review/domain/ReviewImage.java
  src/main/java/com/ureca/review/domain/ReviewLike.java
Labels: 🐞BugFix, 🍎조민정

#27 feature/#113,126-customer,pet-profile-update
  src/main/java/com/ureca/common/util/ValidationUtil.java
  src/main/java/com/ureca/profile/application/service/CustomerService.java
  src/main/java/com/ureca/profile/application/service/PetService.java
  src/main/java/com/ureca/profile/domain/Customer.java
  src/main/java/com/ureca/profile/domain/Pet.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/PetController.java
  src/main/java/com/ureca/profile/presentation/dto/CustomerUpdate.java
  src/main/java/com/ureca/profile/presentation/dto/PetUpdate.java
Labels: ✨ Feature, 🍎조민정

#28 feature/#129-designer-portfolio-update-delete
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/profile/application/service/DesignerService.java
  src/main/java/com/ureca/profile/application/service/PetService.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/domain/Portfolio.java
  src/main/java/com/ureca/profile/domain/PortfolioImg.java
  src/main/java/com/ureca/profile/infrastructure/PortfolioImgRepository.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/dto/BreedCode.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerUpdate.java
  src/main/java/com/ureca/profile/presentation/dto/PortfolioUpdate.java
Labels: ✨ Feature, 🍎조민정

#29 feature/#152-home-view
  src/main/java/com/ureca/home/presentation/HomeController.java
  src/main/java/com/ureca/home/presentation/dto/HomeDesignerDetail.java
  src/main/java/com/ureca/home/presentation/dto/HomeInfo.java
  src/main/java/com/ureca/home/service/HomeService.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
Labels: ✨ Feature, 🍎조민정

#30 Feature/#85 request and estimate
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/estimate/domain/Estimate.java
  src/main/java/com/ureca/estimate/domain/EstimateImage.java
  src/main/java/com/ureca/profile/infrastructure/CommonCodeRepository.java
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/domain/Request.java
  src/main/java/com/ureca/request/domain/RequestAlarm.java
  src/main/java/com/ureca/request/infrastructure/RequestRepository.java
  src/main/java/com/ureca/request/presentation/RequestController.java
  src/main/java/com/ureca/request/presentation/dto/RequestDto.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: ✨ Feature, 🌙최지훈

#31 feature/#127-designer-profile-update
  src/main/java/com/ureca/profile/application/service/CustomerService.java
  src/main/java/com/ureca/profile/application/service/DesignerService.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/domain/Services.java
  src/main/java/com/ureca/profile/infrastructure/CertificateRepository.java
  src/main/java/com/ureca/profile/infrastructure/ServicesRepository.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerUpdate.java
  src/main/java/com/ureca/profile/presentation/dto/ReviewInfo.java
Labels: ✨ Feature, 🍎조민정

#32 Feature/#85 request2
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/presentation/RequestController.java
Labels: ✨ Feature, 🌙최지훈

#33 Feature/#139 estimate
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/infrastructure/EstimateImageRepository.java
  src/main/java/com/ureca/estimate/infrastructure/EstimateRepository.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDtoDetail.java
  src/main/java/com/ureca/request/presentation/RequestController.java
Labels: ✨ Feature, 🌙최지훈

#34 feature/#127-designer-fix
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
Labels: 🐞BugFix, 🍎조민정

#35 feature/#32-cd-test5
  .github/workflows/develop.yml
  appspec.yml
  build/text.txt
  scripts/deploy.sh
Labels: ⚙️ Setting, 🍎조민정

#36 Feature/#122 impl create reservation api
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/common/util/ValidationUtil.java
  src/main/java/com/ureca/config/restTemplate/RestTemplateConfig.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/config/PaymentServerConfig.java
  src/main/java/com/ureca/reservation/domain/Reservation.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
  src/main/java/com/ureca/reservation/presentation/dto/EstimateReservationRequestDto.java
  src/main/java/com/ureca/reservation/presentation/dto/PaymentRequestDto.java
  src/main/java/com/ureca/reservation/presentation/dto/PaymentResponseDto.java
Labels: 👾허건호, ✨ Feature

#37 fix/#85-entity-name
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/domain/Estimate.java
  src/main/java/com/ureca/estimate/domain/EstimateImage.java
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/domain/Request.java
  src/main/java/com/ureca/request/domain/RequestAlarm.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/review/domain/Review.java
  src/main/java/com/ureca/review/domain/ReviewImage.java
  src/main/java/com/ureca/review/domain/ReviewLike.java
Labels: 🌙최지훈, ♻️ Refactor

#38 hotfix/#00-bug-fix
  .github/workflows/develop.yml
  src/main/java/com/ureca/request/infrastructure/RequestRepository.java
Labels: 🐞BugFix, 🍎조민정

#39 hotfix/#00-bug-fix
  .github/workflows/develop.yml
  src/main/java/com/ureca/request/infrastructure/RequestRepository.java
Labels: 🐞BugFix, 🍎조민정

#40 Feature/#86 alarm
  src/main/java/com/ureca/alarm/application/AlarmService.java
  src/main/java/com/ureca/alarm/domain/Alarm.java
  src/main/java/com/ureca/alarm/infrastructure/AlarmRepository.java
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
  src/main/java/com/ureca/alarm/presentation/dto/AlarmDto.java
  src/main/java/com/ureca/common/application/S3Service.java
  src/main/java/com/ureca/estimate/domain/EstimateImage.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateImageDto.java
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/presentation/RequestController.java
Labels: ✨ Feature, 🌙최지훈

#41 Feature/#87 bid category
  src/main/java/com/ureca/alarm/application/AlarmService.java
  src/main/java/com/ureca/alarm/infrastructure/AlarmRepository.java
  src/main/java/com/ureca/alarm/presentation/dto/AlarmDto.java
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateImageDto.java
  src/main/java/com/ureca/profile/infrastructure/BreedsRepository.java
  src/main/java/com/ureca/profile/infrastructure/ServicesRepository.java
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/presentation/RequestController.java
  src/main/java/com/ureca/review/domain/Review.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: ✨ Feature, 🌙최지훈

#42 Feature/#122 impl create reservation api
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
  src/main/java/com/ureca/reservation/presentation/dto/DirectReservationRequestDto.java
Labels: 👾허건호, ✨ Feature

#43 Feature/#178 estimate concurrent
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/domain/Estimate.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDtoDetail.java
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/domain/Request.java
  src/main/java/com/ureca/request/presentation/dto/RequestDto.java
Labels: ✨ Feature, 🌙최지훈

#44 feature/#17-kakao-login
  build.gradle
  src/main/java/com/ureca/login/application/KakaoService.java
  src/main/java/com/ureca/login/application/LoginService.java
  src/main/java/com/ureca/login/presentation/KakaoController.java
  src/main/java/com/ureca/login/presentation/LoginController.java
  src/main/java/com/ureca/login/presentation/dto/KakaoDTO.java
  src/main/java/com/ureca/login/presentation/dto/UserDTO.java
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/profile/domain/Customer.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/infrastructure/CustomerRepository.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/PetController.java
  src/main/resources/static/img/kakao_login_small.png
  src/main/resources/templates/loginPage.html
Labels: ✨ Feature, 🍎조민정

#45 feature/#17-kakao-login-fix
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/config/web/WebConfig.java
Labels: 🐞BugFix, 🍎조민정

#46 feature/#157-bookmark
  appspec.yml
  scripts/deploy.sh
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/domain/Bookmark.java
  src/main/java/com/ureca/profile/infrastructure/BookmarkRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/dto/BookmarkYn.java
Labels: ✨ Feature, 🍎조민정

#47 Fix: Api 오류 수정 및 url 오타 변경
  src/main/java/com/ureca/alarm/infrastructure/AlarmRepository.java
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDtoDetail.java
  src/main/java/com/ureca/request/presentation/RequestController.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
Labels: ✨ Feature, 🌙최지훈

#48 feature/#190-kakao-login-fix
  src/main/java/com/ureca/login/presentation/KakaoController.java
Labels: 🐞BugFix, 🍎조민정

#49 hotfix/#00-cors-fix
  src/main/java/com/ureca/config/web/WebConfig.java
Labels: 🐞BugFix, 🍎조민정

#50 hotfix/#00-swagger
  build.gradle
  src/main/java/com/ureca/config/web/SwaggerConfig.java
  src/main/java/com/ureca/config/web/WebConfig.java
  src/main/java/com/ureca/home/presentation/HomeController.java
  src/main/java/com/ureca/login/presentation/LoginController.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/PetController.java
Labels: ⚙️ Setting, 🍎조민정

#51 Feature/#99 fix api and add for designer api
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/infrastructure/ReservationRepository.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
  src/main/java/com/ureca/reservation/presentation/dto/DesignerInfoDto.java
  src/main/java/com/ureca/reservation/presentation/dto/RequestDetailDto.java
  src/main/java/com/ureca/reservation/presentation/dto/ReservationHistoryResponseDto.java
Labels: 👾허건호, ✨ Feature

#52 hotfix/#00-cors-fix2
  src/main/java/com/ureca/login/presentation/KakaoController.java
Labels: 🐞BugFix, 🍎조민정

#53 feature/#190-kakao-login-cookie
  build.gradle
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/common/response/ApiResponse.java
  src/main/java/com/ureca/common/response/SuccessCode.java
  src/main/java/com/ureca/common/util/CookieUtil.java
  src/main/java/com/ureca/common/util/TokenUtils.java
  src/main/java/com/ureca/login/application/LoginService.java
  src/main/java/com/ureca/login/presentation/KakaoController.java
  src/main/java/com/ureca/login/presentation/LoginController.java
  src/main/java/com/ureca/login/presentation/TestController.java
  src/main/java/com/ureca/login/presentation/dto/AuthConstants.java
  src/main/java/com/ureca/login/presentation/dto/UserDTO.java
Labels: ✨ Feature, 🍎조민정

#54 Feature/#200 estimate api 2
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
  src/main/java/com/ureca/alarm/presentation/dto/AlarmDto.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/presentation/RequestController.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
Labels: 🌙최지훈, ♻️ Refactor

#56 Feature/#174 order data validation api
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
  src/main/java/com/ureca/reservation/presentation/dto/OrderKeysAndAmountDto.java
  src/main/java/com/ureca/reservation/presentation/dto/OrderKeysDto.java
Labels: 👾허건호, ✨ Feature

#57 Fix/#200-api
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/presentation/RequestController.java
Labels: 🐞BugFix, 🌙최지훈

#55 hotfix/#190-kakao-login-cookie
  src/main/java/com/ureca/common/util/CookieUtil.java
  src/main/java/com/ureca/config/web/WebConfig.java
  src/main/java/com/ureca/login/presentation/KakaoController.java
  src/main/java/com/ureca/login/presentation/LoginController.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
Labels: 🐞BugFix, 🍎조민정

#59 Fix/#200-api-2
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: 🐞BugFix, 🌙최지훈

#60 hotfix/#112-customer-view-fix
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
  src/main/java/com/ureca/profile/presentation/dto/BookmarkInfo.java
  src/main/java/com/ureca/profile/presentation/dto/BreedSub.java
Labels: 🐞BugFix, 🍎조민정

#61 hotfix/#112-file-update-fix
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/PetController.java
Labels: 🐞BugFix, 🍎조민정

#62 Fix/#200 api 3
  src/main/java/com/ureca/alarm/application/AlarmService.java
  src/main/java/com/ureca/request/application/RequestService.java
Labels: ✨ Feature, 🌙최지훈

#63 feature/#198-map-search
  src/main/java/com/ureca/home/application/HomeService.java
  src/main/java/com/ureca/home/presentation/HomeController.java
  src/main/java/com/ureca/home/presentation/dto/HomeDesignerDetail.java
  src/main/java/com/ureca/home/presentation/dto/MapDesignerInfo.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
Labels: ✨ Feature, 🍎조민정

#64 fix/#200-api-4
  src/main/java/com/ureca/alarm/application/AlarmService.java
  src/main/java/com/ureca/alarm/domain/Alarm.java
  src/main/java/com/ureca/alarm/infrastructure/AlarmRepository.java
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
  src/main/java/com/ureca/alarm/presentation/dto/AlarmDto.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDtoDetail.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateImageDto.java
  src/main/java/com/ureca/request/presentation/dto/RequestDto.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: 🐞BugFix, 🌙최지훈

#65 Feature/#219 websocket
  build.gradle
  src/main/java/com/ureca/common/websocket/LocationWebSocketHandler.java
  src/main/java/com/ureca/common/websocket/SessionManager.java
  src/main/java/com/ureca/config/web/WebSocketConfig.java
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
  src/main/java/com/ureca/request/presentation/RequestController.java
  src/main/java/com/ureca/request/presentation/dto/RequestDto.java
  src/main/java/com/ureca/review/domain/Enum/AuthorType.java
Labels: ✨ Feature, 🌙최지훈

#66 fix/#200-api-5
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
Labels: 🐞BugFix, 🌙최지훈

#67 Hotfix/#00 modify column data types
  src/main/java/com/ureca/common/util/ValidationUtil.java
  src/main/java/com/ureca/config/web/WebConfig.java
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/profile/domain/Customer.java
  src/main/java/com/ureca/profile/domain/Pet.java
Labels: 🐞BugFix, 🍎조민정

#68 fix/#200-api6
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
  src/main/java/com/ureca/request/presentation/RequestController.java
  src/main/java/com/ureca/request/presentation/dto/RequestDto.java
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/infrastructure/ReviewRepository.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: 🐞BugFix, 🌙최지훈

#69 feature/#219-websocket2
  src/main/java/com/ureca/alarm/application/AlarmService.java
  src/main/java/com/ureca/alarm/presentation/dto/AlarmDto.java
  src/main/java/com/ureca/config/web/WebSocketConfig.java
  src/main/java/com/ureca/estimate/application/EstimateService.java
Labels: 🐞BugFix, ✨ Feature, 🌙최지훈

#70 Feature/#219 websocket3
  src/main/java/com/ureca/common/websocket/LocationWebSocketHandler.java
  src/main/java/com/ureca/review/application/ReviewService.java
Labels: 🐞BugFix, ✨ Feature, 🌙최지훈

#72 fix/#219-websocket
  src/main/java/com/ureca/common/websocket/LocationWebSocketHandler.java
Labels: 🐞BugFix, 🌙최지훈

#75 Feature/#123 fix delete process
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/domain/Reservation.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
  src/main/java/com/ureca/reservation/presentation/dto/OrderIdWithCancelReasonDto.java
  src/main/java/com/ureca/reservation/presentation/dto/PaymentCancelResponseDto.java
Labels: 👾허건호, ✨ Feature

#74 fix/#211-makerequest
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/domain/Estimate.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
  src/main/java/com/ureca/request/application/RequestService.java
Labels: 🐞BugFix, 🌙최지훈

#76 fix/#218-review
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: 🐞BugFix, 🌙최지훈

#78 Feature/#191 customer signup
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/domain/Customer.java
  src/main/java/com/ureca/profile/infrastructure/CustomerRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/dto/CustomerSignup.java
Labels: ✨ Feature, 🍎조민정

#79 hotfix/#112 customer profile review list fix
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/application/ProfileService.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/dto/CustomerViewDesignerProfile.java
  src/main/java/com/ureca/profile/presentation/dto/ReviewInfo.java
Labels: 🐞BugFix, ✨ Feature, 🍎조민정

#80 fix/#218-review2
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: 🐞BugFix, 🌙최지훈

#81 Feature/#191 designer signup
  src/main/java/com/ureca/login/presentation/SignupController.java
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerSignup.java
Labels: 🐞BugFix, ✨ Feature, 🍎조민정

#82 Fix/#214 alarm
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
Labels: 🐞BugFix, 🌙최지훈

#83 Feature/#124 designer payment api
  build/text.txt
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/reservation/application/DesignerPaymentService.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/presentation/PaymentController.java
Labels: 👾허건호, ✨ Feature

#84 fix/#214-alarm2
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
Labels: 🐞BugFix, 🌙최지훈

#85 fix/#214-alarm2-1
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
Labels: 🐞BugFix, 🌙최지훈

#86 fix/#214-alarm 3
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
Labels: 🐞BugFix, 🌙최지훈

#89 Hotfix/#112 customer img test2
  src/main/java/com/ureca/profile/presentation/CustomerController.java
Labels: 🐞BugFix, 🍎조민정

#90 fix/#218-feed-upload
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: 🐞BugFix, 🌙최지훈

#91 feature/#191 kakao signup
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/login/application/KakaoService.java
  src/main/java/com/ureca/login/application/TestService.java
  src/main/java/com/ureca/login/presentation/SignupController.java
  src/main/java/com/ureca/login/presentation/TestController.java
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/infrastructure/CustomerRepository.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
Labels: ✨ Feature, 🍎조민정

#92 feature/#218-image-api
  src/main/java/com/ureca/alarm/application/AlarmService.java
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
  src/main/java/com/ureca/common/application/S3Service.java
  src/main/java/com/ureca/common/presentation/S3Controller.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
Labels: 🐞BugFix, ✨ Feature, 🌙최지훈

#93 hotfix/#114-designer-review-list-fix
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/application/ProfileService.java
  src/main/java/com/ureca/profile/presentation/dto/ReviewInfo.java
Labels: 🐞BugFix, 🍎조민정

#94 Featrue/#218 image api
  src/main/java/com/ureca/profile/infrastructure/CustomerRepository.java
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
  src/main/java/com/ureca/review/presentation/dto/ReviewLikeDto.java
Labels: 🌙최지훈, ♻️ Refactor

#95 Feature/#239 db and response swagger setting for monitoring
  src/main/java/com/ureca/monitoring/presentaion/MonitoringController.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringDesignerController.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringGuardianController.java
  src/main/java/com/ureca/monitoring/presentaion/dto/PetInfoDto.java
  src/main/java/com/ureca/monitoring/presentaion/dto/ProcessStatusDto.java
  src/main/java/com/ureca/monitoring/presentaion/dto/ReservationInfoForDesignerDto.java
  src/main/java/com/ureca/monitoring/presentaion/dto/ReservationInfoForGuardianDto.java
  src/main/java/com/ureca/monitoring/presentaion/dto/StreamingDto.java
  src/main/java/com/ureca/reservation/presentation/PaymentController.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
Labels: 👾허건호, ✨ Feature

#99 Feature/#242 designer register profile
  src/main/java/com/ureca/config/web/WebConfig.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/domain/Price.java
  src/main/java/com/ureca/profile/infrastructure/PriceRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/dto/BreedPriceTime.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerRegister.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerUpdate.java
  src/main/java/com/ureca/profile/presentation/dto/PortfolioInfoUrl.java
  src/main/java/com/ureca/profile/presentation/dto/ProvidedServices.java
Labels: 🐞BugFix, ✨ Feature, 🍎조민정

#96 feature/#184 Streaming 기술 api 연동하여 테스트
  build.gradle
  src/main/java/com/ureca/config/stream/IVSConfig.java
  src/main/java/com/ureca/streaming/application/StreamingService.java
  src/main/java/com/ureca/streaming/domain/StreamErrorResponse.java
  src/main/java/com/ureca/streaming/domain/StreamStartResponse.java
  src/main/java/com/ureca/streaming/domain/StreamingRequest.java
  src/main/java/com/ureca/streaming/infrastructure/StreamRepository.java
Labels: ✨ Feature, 🥕신재현

#100 fix/#218-makefeed
  src/main/java/com/ureca/request/domain/Request.java
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: 🐞BugFix, 🌙최지훈

#102 Fix/#218 makefeed
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDtoDetail.java
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/request/domain/Request.java
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/dto/ReviewDto.java
Labels: 🐞BugFix, ✨ Feature, 🌙최지훈

#103 Fix: 리뷰 생성 dto null 오류 해결
  src/main/java/com/ureca/estimate/application/EstimateService.java
Labels: 🐞BugFix, 🌙최지훈

#104 Fix: #239-fix-response-data
  src/main/java/com/ureca/monitoring/presentaion/MonitoringGuardianController.java
  src/main/java/com/ureca/monitoring/presentaion/dto/PetInfoDto.java
Labels: 👾허건호, ✨ Feature

#105 Feature/#199 address to coordinate
  src/main/java/com/ureca/login/application/ExternalService.java
  src/main/java/com/ureca/login/application/dto/Coordinate.java
  src/main/java/com/ureca/login/presentation/ExternalController.java
  src/main/java/com/ureca/login/presentation/TestController.java
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
Labels: ✨ Feature, 🍎조민정

#107 fix/#210-post-estimate
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDtoDetail.java
Labels: ✨ Feature, 🌙최지훈

#109 feature/#stream
  src/main/java/com/ureca/config/stream/IVSConfig.java
  src/main/java/com/ureca/streaming/application/IVSService.java
  src/main/java/com/ureca/streaming/application/StreamingService.java
  src/main/java/com/ureca/streaming/domain/ChannelInfo.java
  src/main/java/com/ureca/streaming/domain/StreamErrorResponse.java
  src/main/java/com/ureca/streaming/domain/StreamStartResponse.java
  src/main/java/com/ureca/streaming/domain/StreamingRequest.java
  src/main/java/com/ureca/streaming/presentation/StreamController.java
Labels: ✨ Feature, 🥕신재현

#110 hotfix/#246-fix
  src/main/java/com/ureca/profile/application/DesignerService.java
Labels: 🐞BugFix, 🍎조민정

#112 hotfix/#247-file-url-fix-pet
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/profile/presentation/PetController.java
  src/main/java/com/ureca/profile/presentation/dto/PetUpdate.java
Labels: 🐞BugFix, 🍎조민정

#113 fix/#218-multiimage
  src/main/java/com/ureca/review/application/ReviewService.java
Labels: 🐞BugFix, 🌙최지훈

#115 hotfix/#247-file-url-fix-customer
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/dto/CustomerUpdate.java
Labels: 🐞BugFix, 🍎조민정

#116 fix/#218-multiimage
  src/main/java/com/ureca/review/application/ReviewService.java
Labels: 🐞BugFix, 🌙최지훈

#117 Update README.md
  README.md
Labels: ⚙️ Setting, 🌙최지훈

#119 Update README.md
  README.md
Labels: 👀 ETC

#120 Feature/#241 monitoring guardian api impl
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/monitoring/application/MonitoringService.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringController.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringDesignerController.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringGuardianController.java
  src/main/java/com/ureca/profile/infrastructure/CommonCodeRepository.java
  src/main/java/com/ureca/reservation/domain/Reservation.java
  src/main/java/com/ureca/reservation/infrastructure/ReservationRepository.java
Labels: 👾허건호, ✨ Feature

#121 Feature/#249 monitoring client api
  src/main/java/com/ureca/monitoring/application/MonitoringService.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringController.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringDesignerController.java
  src/main/java/com/ureca/monitoring/presentaion/dto/StreamingInfoDto.java
Labels: 👾허건호, ✨ Feature

#122 hotfix/#247-file-url-fix-designer
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/infrastructure/BreedsRepository.java
  src/main/java/com/ureca/profile/infrastructure/CertificateRepository.java
  src/main/java/com/ureca/profile/infrastructure/PriceRepository.java
  src/main/java/com/ureca/profile/infrastructure/ServicesRepository.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerUpdate.java
Labels: 🐞BugFix, 🍎조민정

#123 Hotfix/#247 file url fix designer portfolio
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/infrastructure/PortfolioImgRepository.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/dto/PortfolioUpdate.java
Labels: 🐞BugFix, 🍎조민정

#124 fix/#218-alarm-error
  src/main/java/com/ureca/common/exception/ApiExceptionController.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
Labels: 🐞BugFix, 🌙최지훈

#125 fix/#218-alarm-error-2
  src/main/java/com/ureca/config/web/WebConfig.java
  src/main/java/com/ureca/review/application/ReviewService.java
Labels: 🐞BugFix, 🌙최지훈

#126 fix/#238-fix-status-description
  src/main/java/com/ureca/monitoring/domain/ProcessStatus.java
Labels: 👾허건호, 👀 ETC

#127 feature/#19-business-verify
  src/main/java/com/ureca/login/application/ExternalService.java
  src/main/java/com/ureca/login/application/dto/BusinessRequest.java
  src/main/java/com/ureca/login/application/dto/BusinessResponse.java
  src/main/java/com/ureca/login/presentation/ExternalController.java
Labels: ✨ Feature, 🍎조민정

#128 feature/fix-payment-server-url
  src/main/java/com/ureca/reservation/application/ReservationService.java
Labels: 🐞BugFix, 👾허건호

#129 hotfix/#00-bug-fix-login
  src/main/java/com/ureca/login/application/LoginService.java
Labels: 🐞BugFix, 🍎조민정

#130 Feature/#251- 스트리밍 API 개발
  src/main/java/com/ureca/config/stream/IVSConfig.java
  src/main/java/com/ureca/monitoring/application/MonitoringService.java
  src/main/java/com/ureca/monitoring/domain/Process.java
  src/main/java/com/ureca/monitoring/presentaion/dto/StreamingDto.java
  src/main/java/com/ureca/monitoring/presentaion/dto/StreamingInfoDto.java
  src/main/java/com/ureca/reservation/infrastructure/ReservationRepository.java
  src/main/java/com/ureca/streaming/application/IVSService.java
  src/main/java/com/ureca/streaming/domain/BroadcastChannelInfo.java
  src/main/java/com/ureca/streaming/presentation/StreamController.java
Labels: ✨ Feature, 🥕신재현

#132 fix/fix-resttemplate-config
  build.gradle
  src/main/java/com/ureca/config/restTemplate/RestTemplateConfig.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
Labels: 🐞BugFix, 👾허건호

#133 hotfix/#00-bug-fix-delete
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/profile/infrastructure/PetRepository.java
  src/main/java/com/ureca/profile/presentation/PetController.java
Labels: 🐞BugFix, 🍎조민정

#134 hotfix#244-pet-profile-delete
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/profile/presentation/PetController.java
Labels: 🐞BugFix, 🍎조민정

#135 feature/#249-monitoring-client-api-get-designer-info
  src/main/java/com/ureca/config/restTemplate/RestTemplateConfig.java
  src/main/java/com/ureca/monitoring/application/MonitoringService.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringController.java
  src/main/java/com/ureca/monitoring/presentaion/dto/DesignerInfoDto.java
Labels: 👾허건호, ✨ Feature

#137 fix:#210-datetime
  src/main/java/com/ureca/estimate/application/EstimateService.java
Labels: 🐞BugFix, 🌙최지훈

#138 fix/#210-datetime
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
Labels: 🐞BugFix, 🌙최지훈

#139 fix/#210-putdto
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
  src/main/java/com/ureca/review/application/ReviewService.java
Labels: 🐞BugFix, 🌙최지훈

#140 hotfix/#00-error-log-print
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/presentation/dto/PaymentResponseDto.java
Labels: 🐞BugFix, 👾허건호

#141 feature/#260 - Channel 삭제 API deleteChannel 구현
  src/main/java/com/ureca/streaming/application/IVSService.java
  src/main/java/com/ureca/streaming/presentation/StreamController.java
Labels: ✨ Feature, 🥕신재현

#142 Fix/#210 putdto
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
  src/main/java/com/ureca/profile/infrastructure/CommonCodeRepository.java
  src/main/java/com/ureca/request/application/RequestService.java
Labels: 🐞BugFix, 🌙최지훈

#144 Feature/#261 multi broad cast
  src/main/java/com/ureca/streaming/application/IVSService.java
  src/main/java/com/ureca/streaming/presentation/StreamController.java
Labels: ✨ Feature, 🥕신재현

#145 hotfix/#247-list-url-fix
  src/main/java/com/ureca/profile/application/DesignerService.java
Labels: 🐞BugFix, 🍎조민정

#147 hotfix#244-pet-profile-delete-fix
  src/main/java/com/ureca/estimate/infrastructure/EstimateRepository.java
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/request/infrastructure/RequestRepository.java
Labels: 🐞BugFix, 🍎조민정

#149 hotfix/#247-designer-profile-update-fix
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerUpdate.java
Labels: 🐞BugFix, 🍎조민정

#150 fix/#210-dto
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/request/application/RequestService.java
Labels: 🐞BugFix, 🌙최지훈

#152 Hotfix/#00 add reservation list response fields
  src/main/java/com/ureca/estimate/domain/Estimate.java
  src/main/java/com/ureca/request/domain/Request.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
Labels: 👾허건호, 👀 ETC

#151 fix/#214-list
  src/main/java/com/ureca/alarm/application/AlarmService.java
  src/main/java/com/ureca/alarm/infrastructure/AlarmRepository.java
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
Labels: 🐞BugFix, 🌙최지훈

#154 Feature/#192 spring security
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
  src/main/java/com/ureca/common/application/AuthService.java
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/estimate/presentation/EstimateController.java
  src/main/java/com/ureca/home/presentation/HomeController.java
  src/main/java/com/ureca/login/presentation/SignupController.java
  src/main/java/com/ureca/login/presentation/TestController.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringController.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringDesignerController.java
  src/main/java/com/ureca/monitoring/presentaion/MonitoringGuardianController.java
  src/main/java/com/ureca/profile/infrastructure/CustomerRepository.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/PetController.java
  src/main/java/com/ureca/request/presentation/RequestController.java
  src/main/java/com/ureca/reservation/presentation/PaymentController.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
Labels: 🐞BugFix, 🍎조민정

#155 Hotfix#244 pet designer profile delete fix
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/profile/infrastructure/PetRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/PetController.java
Labels: 🐞BugFix, 🍎조민정

#156 hotfix/#192-user-role
  src/main/java/com/ureca/common/application/AuthService.java
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/login/application/LoginService.java
  src/main/java/com/ureca/login/presentation/LoginController.java
Labels: 🐞BugFix, 🍎조민정

#158 fix/#214-token
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
  src/main/java/com/ureca/review/presentation/dto/ReviewLikeDto.java
Labels: ✨ Feature, 🌙최지훈

#159 hotfix/#192-token-fix
  src/main/java/com/ureca/common/util/TokenUtils.java
  src/main/java/com/ureca/login/application/LoginService.java
  src/main/java/com/ureca/login/presentation/LoginController.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/infrastructure/PortfolioImgRepository.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
Labels: 🐞BugFix, 🍎조민정

#160 hotfix/#00-0-size-error-fix
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
Labels: 🐞BugFix, 👾허건호

#161 fix/#214-token
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/request/application/RequestService.java
  src/main/java/com/ureca/review/application/ReviewService.java
Labels: 🐞BugFix, 🌙최지훈

#162 hotfix#00-profile-update-fix33
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/PetController.java
Labels: 🐞BugFix, 🍎조민정

#164 Fix: 긴급 수정 -> 디자이너 아이디 추가
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/presentation/dto/DesignerInfoDto.java
  src/main/java/com/ureca/reservation/presentation/dto/ReservationHistoryResponseDto.java
Labels: 🐞BugFix, 👾허건호

#163 fix/#214-token-role
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
Labels: 🐞BugFix, 🌙최지훈

#166 hotfix/#00-temp-hot-fix
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
Labels: 🐞BugFix, 👾허건호

#165 fix/#214-token-role
  src/main/java/com/ureca/estimate/application/EstimateService.java
  src/main/java/com/ureca/estimate/presentation/dto/EstimateDto.java
Labels: 🐞BugFix, 🌙최지훈

#168 Fix/#214 new
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
Labels: 🐞BugFix, 🌙최지훈

#169 fix/#214-new
  src/main/java/com/ureca/alarm/presentation/AlarmController.java
Labels: 🐞BugFix, 🌙최지훈

#170 Fix: 불필요 로직 제거
  src/main/java/com/ureca/monitoring/application/MonitoringService.java
Labels: 🐞BugFix, 👾허건호

#171 Fix/#001 refactoring separation
  .github/workflows/develop.yml
  appspec.yml
  scripts/deploy.sh
  src/main/java/com/ureca/profile/application/CustomerService.java
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/application/PetService.java
  src/main/java/com/ureca/profile/application/ProfileService.java
Labels: ♻️ Refactor, 🍎조민정

#172 fix/#002-refactoring-single-responsibility
  src/main/java/com/ureca/profile/application/DesignerService.java
  src/main/java/com/ureca/profile/application/PetService.java
Labels: ♻️ Refactor, 🍎조민정
