Repository Lets-Be-Friendly-Team/daeng-ggu-backend, pull requests merged in 2024-11, with the labels that each got.

#3 feature/#32-ci-test
  .husky/commit-msg
  .husky/pre-commit
Labels: ⚙️ Setting, 🍎조민정

#5 feature/#32-cd-test
  .github/workflows/ci-pipeline.yaml
  .github/workflows/develop.yml
  README.md
  build.gradle
  src/main/java/com/ureca/DaengGuuBackendApplication.java
  src/test/java/com/ureca/DaengGuuBackendApplicationTests.java
Labels: ⚙️ Setting, 🍎조민정

#6 feature/#32-cd-test2
  .github/workflows/develop.yml
  src/main/java/com/ureca/profile/application/.gitkeep
  src/main/java/com/ureca/profile/domain/.gitkeep
  src/main/java/com/ureca/profile/domain/Enum/.gitkeep
  src/main/java/com/ureca/profile/infrastructure/.gitkeep
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/dto/.gitkeep
Labels: 🐞BugFix, 🍎조민정

#7 feature/#32-cd-test3
  appspec.yml
  scripts/deploy.sh
Labels: 🐞BugFix, 🍎조민정

#10 Feat: 프로필 관련 엔티티 추가, DB 연결 확인
  build.gradle
  src/main/java/com/ureca/profile/domain/.gitkeep
  src/main/java/com/ureca/profile/domain/Bookmark.java
  src/main/java/com/ureca/profile/domain/Breeds.java
  src/main/java/com/ureca/profile/domain/Certificate.java
  src/main/java/com/ureca/profile/domain/CommonCode.java
  src/main/java/com/ureca/profile/domain/Customer.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/domain/Enum/.gitkeep
  src/main/java/com/ureca/profile/domain/Img.java
  src/main/java/com/ureca/profile/domain/Pet.java
  src/main/java/com/ureca/profile/domain/Portfolio.java
  src/main/java/com/ureca/profile/domain/Services.java
  src/main/java/com/ureca/profile/infrastructure/.gitkeep
  src/main/java/com/ureca/profile/infrastructure/BookmarkRepository.java
  src/main/java/com/ureca/profile/infrastructure/BreedsRepository.java
  src/main/java/com/ureca/profile/infrastructure/CertificateRepository.java
  src/main/java/com/ureca/profile/infrastructure/CommonCodeRepository.java
  src/main/java/com/ureca/profile/infrastructure/CustomerRepository.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
  src/main/java/com/ureca/profile/infrastructure/ImgRepository.java
  src/main/java/com/ureca/profile/infrastructure/PetRepository.java
  src/main/java/com/ureca/profile/infrastructure/PortfolioRepository.java
  src/main/java/com/ureca/profile/infrastructure/ServicesRepository.java
  src/test/java/com/ureca/EntityTest.java
Labels: ✨ Feature, 🍎조민정

#12 Feature/exception and response setup
  src/main/java/com/ureca/common/exception/ApiException.java
  src/main/java/com/ureca/common/exception/ApiExceptionController.java
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/common/exception/ErrorResponse.java
  src/main/java/com/ureca/common/response/ResponseDto.java
  src/main/java/com/ureca/common/response/ResponseStatus.java
  src/main/java/com/ureca/common/response/ResponseUtil.java
Labels: ⚙️ Setting, 👾허건호

#14 Feature: 견적,견적요청서 엔티티 구현
  src/main/java/com/ureca/estimate/domain/Estimate.java
  src/main/java/com/ureca/request/domain/Request.java
Labels: ✨ Feature, 🌙최지훈

#15 feature/#98-create-reservation-entity
  src/main/java/com/ureca/reservation/domain/Reservation.java
Labels: 👾허건호, ✨ Feature

#16 Fix: 변수명 수정
  src/main/java/com/ureca/request/domain/Request.java
Labels: 🌙최지훈, ♻️ Refactor

#17 feature/#21-cudtomer-profile-view
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/profile/application/.gitkeep
  src/main/java/com/ureca/profile/application/service/CustomerService.java
  src/main/java/com/ureca/profile/domain/Customer.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/infrastructure/BookmarkRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/dto/.gitkeep
  src/main/java/com/ureca/profile/presentation/dto/BookmarkInfo.java
  src/main/java/com/ureca/profile/presentation/dto/CustomerDetail.java
  src/main/java/com/ureca/profile/presentation/dto/CustomerProfile.java
  src/main/java/com/ureca/profile/presentation/dto/CustomerUpdate.java
  src/main/java/com/ureca/profile/presentation/dto/PetInfo.java
  src/main/java/com/ureca/profile/presentation/dto/ReviewInfo.java
  src/main/java/com/ureca/review/domain/Review.java
  src/main/java/com/ureca/review/infrastructure/ReviewRepository.java
Labels: ✨ Feature, 🍎조민정

#18 Feature/#99 impl get reservation list api
  src/main/java/com/ureca/common/exception/ApiExceptionController.java
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/domain/Reservation.java
  src/main/java/com/ureca/reservation/infrastructure/ReservationRepository.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
  src/main/java/com/ureca/reservation/presentation/dto/RequestDetailDto.java
  src/main/java/com/ureca/reservation/presentation/dto/ReservationHistoryResponseDto.java
Labels: 👾허건호, ✨ Feature

#19 feature/#99-fix-get-reservation-list-api
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/presentation/dto/DesignerInfoDto.java
  src/main/java/com/ureca/reservation/presentation/dto/ReservationHistoryResponseDto.java
Labels: 👾허건호, ✨ Feature

#20 Feature/#100 impl find available reservation time api
  src/main/java/com/ureca/common/exception/ErrorCode.java
  src/main/java/com/ureca/common/util/ValidationUtil.java
  src/main/java/com/ureca/reservation/application/ReservationService.java
  src/main/java/com/ureca/reservation/infrastructure/ReservationRepository.java
  src/main/java/com/ureca/reservation/presentation/ReservationController.java
  src/main/java/com/ureca/reservation/presentation/dto/DesignerAvailableDatesResponseDto.java
  src/main/java/com/ureca/reservation/presentation/dto/ReservationInfo.java
Labels: 👾허건호, ✨ Feature

#21 feature/#26-designer-profile-view
  src/main/java/com/ureca/profile/application/service/CustomerService.java
  src/main/java/com/ureca/profile/application/service/DesignerService.java
  src/main/java/com/ureca/profile/domain/Designer.java
  src/main/java/com/ureca/profile/infrastructure/CertificateRepository.java
  src/main/java/com/ureca/profile/infrastructure/DesignerRepository.java
  src/main/java/com/ureca/profile/infrastructure/ImgRepository.java
  src/main/java/com/ureca/profile/infrastructure/PortfolioRepository.java
  src/main/java/com/ureca/profile/presentation/CustomerController.java
  src/main/java/com/ureca/profile/presentation/DesignerController.java
  src/main/java/com/ureca/profile/presentation/dto/Breed.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerDetail.java
  src/main/java/com/ureca/profile/presentation/dto/DesignerProfile.java
  src/main/java/com/ureca/profile/presentation/dto/PortfolioDetail.java
  src/main/java/com/ureca/profile/presentation/dto/PortfolioInfo.java
  src/main/java/com/ureca/profile/presentation/dto/ReviewInfo.java
  src/main/java/com/ureca/profile/presentation/dto/Service.java
  src/main/java/com/ureca/review/domain/Review.java
Labels: ✨ Feature, 🍎조민정

#22 feature/#22-pet-profile-view
  src/main/java/com/ureca/profile/application/service/PetService.java
  src/main/java/com/ureca/profile/presentation/PetController.java
  src/main/java/com/ureca/profile/presentation/dto/PetDetail.java
Labels: ✨ Feature, 🍎조민정

#24 feature/#81-review3
  src/main/java/com/ureca/review/application/ReviewService.java
  src/main/java/com/ureca/review/presentation/ReviewController.java
Labels: ✨ Feature, 🌙최지훈

#25 feature #148 create base entity
  src/main/java/com/ureca/common/entity/BaseEntity.java
Labels: 👾허건호, 👀 ETC
